### ISSUE TITLE
Multiple issues with Redis cluster

### ISSUE THREAD

**Issue by pfyod** [micronaut-projects/micronaut-redis#1]
1. Redis cluster cannot be used as cache because `RedisConnectionUtil` expects to always have a named `StatefulRedisClusterConnection`
2. Even if one wants, it's not possible to create a named `StatefulRedisClusterConnection` because it's not supported by `NamedRedisClientFactory`
3. `RedisHealthIndicator` only checks health of `RedisClient` instances (and not `RedisClusterClient`)

**Comment by zhenchuan** [comment]
+1

**Comment by ddrao** [comment]
Is there an update on this issue?
