### ISSUE TITLE
Support lettuce latency metrics

### ISSUE THREAD

**Issue by racevedoo** [micronaut-projects/micronaut-redis#121]
Hi all!

Are there any plans to support lettuce [command latency metrics](https://github.com/lettuce-io/lettuce-core/wiki/Command-Latency-Metrics)? Shouldn't be too hard to implement using micrometer.

**Comment by ilopmar** [comment]
Not yet, but of course PRs welcome :)

**Comment by racevedoo** [comment]
Sure! I'll try to come up with a draft

**Comment by racevedoo** [comment]
@ilopmar seems like lettuce 6.0 changed the way to collect metrics a bit, as stated [here](https://github.com/lettuce-io/lettuce-core/releases/tag/6.0.0.RELEASE).

I see that there's an open [PR](https://github.com/micronaut-projects/micronaut-redis/pull/123) that bumps the version to 6.0.1, so I'd like to start implementing this using 6.0 already. Is there any problem? How should I proceed? Thanks!!

**Comment by graemerocher** [comment]
@ilopmar we will need to bump the major version of the project

**Comment by ilopmar** [comment]
Before we can bump a major version of a dependency and include it in a minor Micronaut version, we need to make sure that there are no breaking changes in that module. In case there are breaking changes we need to think carefully if they will accept users' applications and how. I see that the PR with the upgrade pass all the test, that's a good start :-)

Another thing that we need to test before the upgrade is the GraalVM integration. We already have a [test application](https://github.com/micronaut-graal-tests/micronaut-redis-graal) so we need to use it and make sure everything still works.

Yes, you can start working on that and we could include a major version of this module in Micronaut 2.3.

**Comment by ilopmar** [comment]
Upgraded to Lettuce 6.0.2 in #123 and released in Micronaut Redis 4.0.0

**Comment by racevedoo** [comment]
@ilopmar do we support latency metrics with the upgrade? I guess that was the original issue

**Comment by ilopmar** [comment]
No, there is nothing built-it for doing that. I though it was only a matter of upgrading to 6.0.
