### ISSUE TITLE
Cannot connect to Google Memory Store - Redis

### ISSUE THREAD

**Issue by mkfuri** [micronaut-projects/micronaut-redis#169]
### Steps to Reproduce

1. Deploy an app into Google Cloud that it tries to connect to Memory Store with Redis 

### Expected Behaviour

Until micronaut-redis 4.x the app connects to Memory Store without problems

### Actual Behaviour

When I updated to micronaut 2.4, micronaut-redis was updates to version 4.0. Then I tried to deploy the app into Google Cloud but it didn't start because the redis-client couldn't connect to Memory Store. I received  the following message "ERR unknown command `client`, with args beginning with: `setname`, `bull:cGVyc2lzdA==`"

The problem is that Google Cloud Memory Store blocks certain commands as `Client`. https://cloud.google.com/memorystore/docs/redis/product-constraints

I asked in Lettuce's gitter channel and they answered me the following message

![image](https://user-images.githubusercontent.com/13698252/111837756-1d8c1d00-88d7-11eb-8e60-e323149bce91.png)

I think that micronaut-redis is setting the client name and It is not posible to let it blank

### Environment Information

- **Micronaut Version:** 2.4

**Comment by graemerocher** [comment]
as far as I am aware Micronaut Redis is not setting the client name anywhere

**Comment by mkfuri** [comment]
@graemerocher what I saw is that in `AbstractRedisConfiguration` and in `NamedRedisServersConfiguration` are setting the clientName in the constructor. Because both classes extend from `RedisURI` this action sets the client name that use Lettuce in `StatefulRedisConnectionImpl` and in `RedisServerAsyncCommands`

Micronaut only use this attribute to set the bean name in `NamedRedisClientFactory`

```
 /**
     * Finds named {@link ClientResources} or uses default if exists.
     * @param config named config
     * @return named The ClientResources
     */
    private @Nullable ClientResources getClientResources(NamedRedisServersConfiguration config) {
        return beanLocator.findBean(ClientResources.class, Qualifiers.byName(config.getClientName())).orElse(this.defaultClientResources);
    }

    /**
     * Finds named {@link RedisClient}.
     * @param config named config
     * @return named The RedisClient
     */
    private RedisClient getRedisClient(NamedRedisServersConfiguration config) {
        return beanLocator.getBean(RedisClient.class, Qualifiers.byName(config.getClientName()));
    }
```

Perhaps Micronaut can have two different attributes, one for client name and other for bean name and in the case of `DefaultRedisConfiguration` we can avoid to set the client name with the `ENVIROMENT.DEFAUT_NAME`.

```
/**
     * Constructor.
     */
    protected AbstractRedisConfiguration() {
        setClientName(Environment.DEFAULT_NAME);
        setPort(RedisURI.DEFAULT_REDIS_PORT);
        setHost("localhost"); // localhost by default
    }
```

Realy I don't understand what changes between Lettuce 5.x and 6.x

**Comment by mkfuri** [comment]
@graemerocher I tried with the following chances and It works fine into Google Cloud and Memory Store

```
public abstract class AbstractRedisConfiguration extends RedisURI {

    private RedisURI uri;
    private List<RedisURI> uris = Collections.emptyList();
    private Integer ioThreadPoolSize;
    private Integer computationThreadPoolSize;
    private String name;
    private String clientName;
    
    /**
     * Constructor.
     */
    protected AbstractRedisConfiguration() {
        setName(Environment.DEFAULT_NAME);
        setPort(RedisURI.DEFAULT_REDIS_PORT);
        setHost("localhost"); // localhost by default
    }
....
}
```

```
@EachProperty(value = RedisSetting.REDIS_SERVERS)
public class NamedRedisServersConfiguration extends AbstractRedisConfiguration {

    /**
     * Constructor.
     * @param name name from configuration
     */
    public NamedRedisServersConfiguration(@Parameter String name) {
        setName(name);
    }
}
```

`NamedRedisClientFactory`

```
/**
     * Finds named {@link ClientResources} or uses default if exists.
     * @param config named config
     * @return named The ClientResources
     */
    private @Nullable ClientResources getClientResources(NamedRedisServersConfiguration config) {
        return beanLocator.findBean(ClientResources.class, Qualifiers.byName(config.getName())).orElse(this.defaultClientResources);
    }

    /**
     * Finds named {@link RedisClient}.
     * @param config named config
     * @return named The RedisClient
     */
    private RedisClient getRedisClient(NamedRedisServersConfiguration config) {
        return beanLocator.getBean(RedisClient.class, Qualifiers.byName(config.getName()));
    }
```

what do you think?

**Comment by graemerocher** [comment]
PRs welcome
