### ISSUE TITLE
Can't deserialize generic types with BeanIntrospectionModule

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-redis#21]
The `BeanIntrospectionModule` currently implements `SimpleModule` which specifies in its javadocs:

> WARNING: when registering JsonSerializers and JsonDeserializers, only type erased Class is compared: this means that usually you should NOT use this implementation for registering structured types such as Collections or Maps: this because parametric type information will not be considered and you may end up having "wrong" handler for your type. What you need to do, instead, is to implement com.fasterxml.jackson.databind.deser.Deserializers and/or com.fasterxml.jackson.databind.ser.Serializers callbacks to match full type signatures (with JavaType).

It seems that the interfaces specified there need to be implemented for this to work properly with generics.

Example (in Kotlin with KotlinTest):
```kotlin
data class SomeClass(val name: String)

val list = listOf(SomeClass("one"), SomeClass("two"))

class ObjectSerializerTest : StringSpec({
	 "it serializes a list of data classes" {
		val ctx = ApplicationContext.run()
		val ser = ctx.getBean(JacksonObjectSerializer::class.java)

		ser.serialize(list).get().commonToUtf8String() shouldBe """[{"name":"one"},{"name":"two"}]"""
	}

	"it deserializes a list of data classes" {
		val ctx = ApplicationContext.run()
		val ser = ctx.getBean(JacksonObjectSerializer::class.java)

		ser.deserialize("""[{"name":"one"},{"name":"two"}]""".toByteArray(), List::class.java).get() shouldBe list
	}
})
```
Serialization works, but deserialization gives:
`expected: [SomeClass(name=one), SomeClass(name=two)] but was: [{"name"="one"}, {"name"="two"}]`

I think because in the RedisCache implementation:
```
    protected <T> Optional<T> getValue(Argument<T> requiredType, SyncCacheCommands commands, byte[] serializedKey) {
        byte[] data = commands.get(serializedKey);
        if (expireAfterAccess != null) {
            commands.expire(serializedKey, expireAfterAccess);
        }
        if (data != null) {
            return valueSerializer.deserialize(data, requiredType.getType());
        } else {

            return Optional.empty();
        }
    }
```
`requiredType.getType()` just gives `List::class.java` which would explain why the cast fails in the cache usage.

**Comment by graemerocher** [comment]
This issue requires an upgrade to Micronaut 2.0 which has a deserialize method that supports generic types

**Comment by graemerocher** [comment]
PR submitted https://github.com/micronaut-projects/micronaut-redis/pull/63
