### ISSUE TITLE
RedisHealthIndicator doesn't use an ExecutorService and block on EventLoop threads

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-redis#219]
### Expected Behavior

This indicator should use the IO ExecutorService (like JdbcIndicator does) or other mecanism to prevent to block on EventLoop Thread when /health or /health/readiness endpoint is called

### Actual Behaviour

This indicator is making a blocking call (RedisClient#connect) on EventLoop thread when called from /health/readiness endpoint.
I found that issue using [BlockHound](https://github.com/reactor/BlockHound)

### Steps To Reproduce

1. Create a simple demo app [here](https://micronaut.io/launch) with redis and management features
2. Use [BlockHound](https://github.com/reactor/BlockHound) at startup 
```java
public class Application {

    public static void main(String[] args) {
        // This is done only for this demo, can't be used on production
        BlockHound.install(builder ->
            builder
                 // we allow some known and irrelevant blocking calls
                .allowBlockingCallsInside("com.fasterxml.jackson.databind.ObjectMapper", "findModules")
                .allowBlockingCallsInside("io.micronaut.core.io.service.SoftServiceLoader$ServiceLoaderIterator", "hasNext")
        );
        Micronaut.run(Application.class, args);
    }
}
```
3. Call the endpoint http://localhost:8080/health

### Example Application

https://github.com/ggerbaud/demo-micronaut-redis-eventloop

### Version

3.0.0 but also 2.5.11

**Comment by pgressa** [comment]
Related to #184
