### ISSUE TITLE
Create BOM

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-redis#266]
### Issue description

Create BOM for redis

**Comment by timyates** [comment]
Are we creating BOMs for single module projects?

**Comment by sdelamo** [comment]
since this module has `lettuce` as `api` scope. I think it would be best to expose a BOM instead of managing it in core: 

https://github.com/micronaut-projects/micronaut-core/blob/3.3.x/gradle/libs.versions.toml#L69

What do you think?

**Comment by sdelamo** [comment]
thoughts @melix ?

**Comment by melix** [comment]
Yes, we said that we also want to provide BOMs for single module projects.
