### ISSUE TITLE
Async Redis cache hangs indefinitely when deserialization fails

### ISSUE THREAD

**Issue by MisterSerious** [micronaut-projects/micronaut-redis#27]
When running Redis caching with a CompletableFuture, if deserialization fails the completable future never completes.

To reproduce:
1. Pull this repo https://github.com/MisterSerious/redisfuture
2. Run docker-compose up
4. Run the test

**Comment by vemilyus** [comment]
Hi there, I'm preparing a pull request with the fix for this issue. Could you elaborate on what makes the deserialization in your example fail?

**Comment by vemilyus** [comment]
Work done in PR #37

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by graemerocher** [comment]
Thanks for the contribution
