### ISSUE TITLE
RedisConnectionUtil.findRedisConnection bug

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-redis#30]
At https://github.com/micronaut-projects/micronaut-redis/blob/master/redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/RedisConnectionUtil.java#L53 a bean of type `StatefulRedisClusterConnection.class` is looked up but shouldnt it be of type `StatefulRedisConnection.class` instead?
It seems like a bug since the same lookup is made 3 lines above.

Eg for caching, which use this method, it is currently only possible to use a redis that is setup using a default conf, a named redis server won't work since `NamedRedisClientFactory` returns connections of type `StatefulRedisConnection`.

**Comment by graemerocher** [comment]
I think it falls back to `StatefulRedisConnection` if no `StatefulRedisClusterConnection`

Is this causing a problem for you?

**Comment by luckyswede** [comment]
It doesn't if `serverName` is set, in which case it throws a `ConfigurationException`. Thats where I think there is a bug, the **second** 
`beanLocator.findBean(StatefulRedisClusterConnection.class, Qualifiers.byName(name))`
should be looking for a `StatefulRedisConnection.class`.
