### ISSUE TITLE
Redis hangs under GraalVM for 3.6.4-SNAPSHOT

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-redis#319]
We have a test for GraalVM which builds a native image of a simple Redis backed application and then checks the endpoints work as expected.

The project can be found over here:

https://github.com/micronaut-graal-tests/micronaut-redis-graal/tree/3.6.x

This is executed on GitLab, but when the endpoint is called, the application simply hangs

https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/3024111190

If we change the log level to DEBUG, there are lots of warnings about Netty, but I don't know if these are related...

Running with `./gradlew -Pagent run` and hitting the endpoint generates a lot of agent files, and I was told that copying these into `src/main/resources/META-INF` fixed the issue, however that's not what I'm seeing under OSX...  I'm then seeing errors looking up JFR events...

### Steps to Reproduce

1. Clone https://github.com/micronaut-graal-tests/micronaut-redis-graal
2. Check out the 3.6.x branch
3. Change the logger in src/main/resources to trace
4. Start redis locally: `docker run -p 6379:6379 -d redis`
5. Use GraalVM CE 22.2.r11 (or r17)
6. Run ./gradlew nativeCompile
7. Run build/native/nativeCompile/redis
8. hit http://localhost:8080/set

### Expected Behaviour

It should return an empty response, then hitting http://localhost:8080/get should return "Hello World"

### Actual Behaviour

It just hangs, and never responds

### Environment Information

Fails on both ARM and X86 OSX machines

```
❯ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06, mixed mode)
```

Micronaut 3.6.x

**Comment by salvob** [comment]
I have the same problem with micronaut 3.7.1
Any updates?

**Comment by timyates** [comment]
This works with Micronaut 4.0.x

I'm going to close this
