### ISSUE TITLE
Redis Support Connecting to ElastiCache with Master/Replica

### ISSUE THREAD

**Issue by RealityCtrl** [micronaut-projects/micronaut-redis#430]
### Feature description

AWS Elasticache Supports read replicas [without using clustering mode](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.html) which is [supported by lettuce](https://github.com/lettuce-io/lettuce-core/blob/6.2.5.RELEASE/src/test/java/io/lettuce/examples/ConnectToMasterSlaveUsingElastiCacheCluster.java) using the StatefulRedisMasterReplicaConnection class but micronaut does not expose any configuration to support this configuration.
This means we can only connect to the master node and not spread the load of reading the cached values around the replicas.

**Comment by Mike-Svendsen-IL** [comment]
I'm looking into implementing this and getting a PR open.
