### ISSUE TITLE
When a redis session is introduced, the business operation is processed in lettuce-nioeventloop threads 

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-redis#45]
When the redis session is opened, the io executors configuration does not take effect, and the running thread pool is lettuce-nioeventloop 

# Environment Information

- **Operating System**: windows
- **Micronaut Version:** 1.3.6
- **JDK Version:** jdk8

### Steps to Reproduce

```
@Controller("/demo")
public class DemoResource  {

  static Logger log = LoggerFactory.getLogger(DemoResource.class);
  
  @Get("/hello")
  public String hello() {
    log.info("Hello world!");
    return "Hello world!";
  }
}
```

1. Close redis session 

11:50:54.814 [nioEventLoopGroup-1-2] DEBUG i.m.s.h.CookieHttpSessionIdGenerator - cookie value: NmQ2YjBhMGYtZDVmMC00NzhjLTk3Y2MtNzY4OTg0NGNkMjBm
11:50:54.815 [nioEventLoopGroup-1-2] DEBUG i.m.s.http.CookieHttpSessionStrategy - path 6d6b0a0f-d5f0-478c-97cc-7689844cd20f, session id: /demo
11:50:54.884 [**_pool-1-thread-4_**] INFO  hello.world.DemoResource - Hello world!

2. Open redis session

11:53:48.544 [nioEventLoopGroup-5-2] DEBUG i.m.s.h.CookieHttpSessionIdGenerator - cookie value: NmQ2YjBhMGYtZDVmMC00NzhjLTk3Y2MtNzY4OTg0NGNkMjBm
11:53:48.545 [nioEventLoopGroup-5-2] DEBUG i.m.s.http.CookieHttpSessionStrategy - path 6d6b0a0f-d5f0-478c-97cc-7689844cd20f, session id: /demo
11:53:48.548 [**_lettuce-nioEventLoop-4-1_**] INFO  hello.world.DemoResource - Hello world!

**Comment by vnesek** [comment]
Same problem here, making a lot of problems as threads are getting exhausted

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by vnesek** [comment]
We have it running in production, debugging it right now. Roundtrip to redis is more than a second for simple get queries in a same kubernetes cluster. We're using it with @Cacheable and directly for some custom operations.

 It seams that all reactive calls get executed in lettuce pool although we specify schedulers (using project reactor). Is there any way to at least increase a number of threads in letucce pool?

**Comment by graemerocher** [comment]
Yes you can define a bean of type `ClientResources`. For example:

```java
@Factory
class ClientResourcesFactory {
     @Singleton 
     ClientResources clientResources() {
            return ClientResources.builder().ioThreadPoolSize(30).build(); // size configurable
     }

}
```

**Comment by vnesek** [comment]
Tx Graeme,

I think I found a source of problems... We've got an RateLimiter method interceptor:

```kotlin
@Target(FUNCTION)
@Retention(RUNTIME)
@Around
@Type(RateLimitInterceptor::class)
@Internal
annotation class RateLimit(
    val cost: Int = 1,
    val limit: String = ""
)

Inside of it was a blocking call to redis connection. I think it got stuck quite often as it was called on methods with redis @Cacheable somewhere up or down call hierarchy.

Is there a way to make MethodInterceptor ... reactive? I guess if a return type of intercepted method is reactive we could wrap around it.

**Comment by graemerocher** [comment]
That is right you would have to check the return type.

**Comment by vnesek** [comment]
We're logging threads now and apparently anything reactive touching letucce get's executed on it's pool regardless of schedulers specified by (Mono|Flux)::scheduleOn. I don't think that is correct behaviour, will try to make a simple test case demonstrating it.

If anyone is interested in reactive methodinterceptor, here's an example:
```kotlin
@Singleton
@Requires(property = "micronaut.rate.enabled", notEquals = "false")
class RateLimitInterceptor(
    private val rateLimiter: RateLimiter,
    private val rateLimitClientResolver: RateLimitClientResolver
) : MethodInterceptor<Any, Any> {

    @Throws(RateLimitExceededException::class)
    override fun intercept(context: MethodInvocationContext<Any, Any>): Any {
        val rl = context.getAnnotation(RateLimit::class.java)!!
        val limit = rl["limit", String::class.java]
        if (limit.isPresent) {
            val limitValue = limit.get()
            if (limitValue.isNotBlank()) {
                val clientId = rateLimitClientResolver.getClientId()
                val cost = rl["cost", Int::class.java]
                if (clientId.isPresent) {
                    val costValue = cost.orElse(1)
                    val checkLimit = Runnable {
                        if (!rateLimiter.limit(clientId.get(), limitValue, costValue)) {
                            throw RateLimitExceededException(limitValue, costValue)
                        }
                    }

                    val returnType = context.returnType.type
                    return when {
                        returnType.isAssignableFrom(Mono::class.java) -> {
                            val next = context.proceed() as? Mono<*>
                            if (next != null) next.doFirst(checkLimit) else Mono.empty<Void>()
                        }
                        returnType.isAssignableFrom(Flux::class.java) -> {
                            val next = context.proceed() as? Flux<*>
                            if (next != null) next.doFirst(checkLimit) else Flux.empty<Void>()
                        }
                        else -> {
                            checkLimit.run()
                            context.proceed()
                        }
                    }
                }
            }
        }
        return context.proceed()
    }
}
```

**Comment by dstepanov** [comment]
This might have been fixed with the refactoring of `CacheInterceptor`

**Comment by sdelamo** [comment]
@chenjpu could you confirm if this is fixed for you?

**Comment by davidhiendl** [comment]
I believe I've also experienced a issue related to this: when using Redis Session in combination with `HttpServerFilter` or `SecurityRule` the filters are executed on the `lettuce-nioEventLoop` pool. The business logic in the controllers however is executed correctly on the thread pool specified by `@ExecuteOn(...)`

**Comment by chenjpu** [comment]
@sdelamo I'm sorry I did n' t respond in time 

I used the latest version of the test results ,The problem has been fixed by ```@ExecuteOn(...)```.

demo
```
@Controller("/demo")
public class DemoResource {

  static Logger log = LoggerFactory.getLogger(DemoResource.class);
  
  @Get("/hello")
  @ExecuteOn(TaskExecutors.IO)
  public String hello(Session session) {
    log.info("Hello world!");
    return "Hello world!";
  }
}
```
