### ISSUE TITLE
How to configure ClientResources on RedisClient bean 

### ISSUE THREAD

**Issue by shashanka981** [micronaut-projects/micronaut-redis#52]
Hi,

This is more of a question/enhancement.

Lettuce offers a way to configure client resources (https://lettuce.io/core/release/reference/index.html#clientresources.using-and-reusing-clientresources) on RedisClient class. However, we lose the flexibility of configuring client resources if we get a bean from Micronuat-redis (as of version 2.1.0). 

Any reasons for not allowing Client resources to be configurable ? Can this be enhanced as it will allow for customizations ?

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-redis/pull/47
