### ISSUE TITLE
DefaultRedisClusterClientFactory uses default StringCodec

### ISSUE THREAD

**Issue by herisn23** [micronaut-projects/micronaut-redis#536]
There is a issue with RedisCodec when using different environment configuration (cluster, non-cluster) when using custom codec.

When developing on localhost i use standalone non-cluster redis. This configuration uses codec created in my factory class.

```kotlin
@Singleton
@Replaces(RedisCodec::class)
@Primary
fun serializedObjectCodec(): RedisCodec<String, Any> =
    createJdkSerializerCodec()
```

But `DefaultRedisClusterClientFactory` bypassing this codec because not provide codec when call `client.connect()` like in non-cluster configuration.

This behaviour causes errors on kubernetes where redis-cluster running, because connection uses default lettuce StringCodec instead of user-defined codec.

It is possible to inherit AbstractRedisClientFactory<K, V> like in DefaultRedisClientFactory and create StatefulRedisClusterConnection with user defined codec?

For now i have work around for this issue with custom configuration but i wont have this code in my app.

```kotlin
@Bean(preDestroy = "close")
@Replaces(StatefulRedisClusterConnection::class)
@Singleton
@Primary
fun redisConnection(
    @Primary codec: RedisCodec<String, Any>,
    @Primary redisClient: RedisClusterClient
): StatefulRedisClusterConnection<String, Any> {
    return redisClient.connect(codec)
}
```

This is the class which, i think, need improvements.

https://github.com/micronaut-projects/micronaut-redis/blob/80009dc2bec103e499e992e5ddfdfc6d8513adb7/redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/DefaultRedisClusterClientFactory.java#L45

**Comment by graemerocher** [comment]
seems like you diagnosed the problem, would you send a PR?

**Comment by yibo-long** [comment]
@herisn23 are you interested in a PR? Otherwise I also intend to contribute on this as we faced with this issue too.

**Comment by yibo-long** [comment]
Created https://github.com/micronaut-projects/micronaut-redis/pull/571, thanks!
