### ISSUE TITLE
When will micronaut-redis 6.5.x be released?

### ISSUE THREAD

**Issue by aozmen121** [micronaut-projects/micronaut-redis#556]
### Feature description

Is there a timeline as to when the [micronaut-redis](https://github.com/micronaut-projects/micronaut-redis) version 6.5.x be released?

**Comment by aozmen121** [comment]
@sdelamo & @graemerocher FYI do we know when 6.5.x be released?

**Comment by graemerocher** [comment]
when this build completes https://github.com/micronaut-projects/micronaut-redis/actions/runs/10268092583

**Comment by aozmen121** [comment]
@graemerocher Thank you, but the build has failed around java-docs generation issue with error `unknown tag T` on method:
```
    /**
     * @param requiredType
     * @param serializedKey
     * @param <T>
     * @return Optional<T>
     */
    protected abstract <T> Optional<T> getValue(Argument<T> requiredType, byte[] serializedKey);
```
Looks like the fix might be to update the java docs to just mention that its `optional value based on argument type`

Error:
```
/home/runner/work/micronaut-redis/micronaut-redis/redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/cache/AbstractRedisCache.java:219: error: unknown tag: T
     * @return Optional<T>
                       ^
```

**Comment by graemerocher** [comment]
looking into it, don't think it is a javadoc error

**Comment by sdelamo** [comment]
https://github.com/micronaut-projects/micronaut-redis/releases/tag/v6.5.0 is out.
