### ISSUE TITLE
Micronaut-Redis waits forever to select database or authenticate if Redis does not respond to commands

### ISSUE THREAD

**Issue by andersaaberg** [micronaut-projects/micronaut-redis#91]
### Steps to Reproduce
See README.md at https://github.com/andersaaberg/test-redis-timeout

#### How to reproduce that Micronaut-Redis waits forever to select database or authenticate
Listen on Redis port in another terminal:
`nc -l 6379 -C`

Run micronaut application:
`./gradlew run`

Call controller in another terminal:
`curl http://localhost/test`

Expected result:
Should throw exception after 5s, but waits forever. This problem does not exist in Lettuce, so it must be caused by Micronaut-Redis

#### How this project is created
```
sdk u micronaut 2.0.1
mn create-app --lang=groovy test-redis-timeout
cd test-redis-timeout
mn create-controller Test
```

Add the following dependency to build.gradle:
`implementation("io.micronaut.redis:micronaut-redis-lettuce")`

Add the following configuration to application.yml:
```yaml
redis:
  uri: redis://localhost/1 # or redis://password@localhost
  timeout: 5s
```

Modify TestController:
```java
package test.redis.timeout

import io.lettuce.core.api.StatefulRedisConnection
import io.lettuce.core.api.sync.RedisCommands
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get

import javax.inject.Inject

@Controller("/test")
class TestController {

    @Inject
    StatefulRedisConnection<String, String> statefulRedisConnection

    @Get(uri="/", produces="text/plain")
    String index() {
        RedisCommands redisCommands = statefulRedisConnection.sync()
        redisCommands.ping() // never executed if redis accepts TCP connection but does not respond
        "Example Response"
    }
}
```

### Expected Behaviour
Exception thrown due to timeout

### Actual Behaviour
Hangs forever on statefulRedisConnection.sync()

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 2.0.1
- **JDK Version:** 1.8.0_252

### Example Application
https://github.com/andersaaberg/test-redis-timeout

**Comment by alvarosanchez** [comment]
Nothing to do with micronaut-redis. The problem is that the controller is blocking the event loop.

If you annotate the `index()` method with `@ExecuteOn(TaskExecutors.IO)` (as documented in https://docs.micronaut.io/latest/guide/index.html#upgrading), then after 5 seconds it will throw the following exception: `io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379`
